### ISSUE TITLE
On the term "edge native"

### ISSUE THREAD

**Issue by ept** [edge-native/website#1]
I love what you're doing here, articulating principles that I very much agree with. There is a lot of overlap between the edge native principles and the [local-first principles](https://www.inkandswitch.com/local-first.html) (I see you have linked to the article). Since there is so much overlap, I was wondering if it would make sense to fold the two terms into one, and put effort into promoting that one term.

As you have rightly pointed out, our local-first article has approached the topic from one particular point of view, which is centered on one person's files on their personal computing devices. You have come from another perspective, which is interaction between controllers, actuators and sensors within the same factory building. I think it's great to bring together diverse perspectives, and I hope we can find a way of presenting the principles that speaks to people working on a wide range of different computing systems.

I personally am not a big fan of the term "edge", because it seems to mean very different things to different people. If you search about edge computing online, all the results you get are incredibly vague and buzzwordy. Does "edge" simply mean [small datacenters](https://www.zdnet.com/article/where-the-edge-is-in-edge-computing-why-it-matters-and-how-we-use-it/)? Does it refer to [servers that are part of a CDN](https://www.cloudflare.com/learning/cdn/glossary/edge-server/), or [computing resources in 5G networks](https://www.vodafone.com/business/news-and-insights/blog/gigabit-thinking/your-competitive-edge-5G-and-edge-computing-unlock-new-possibilities), or doing [machine learning on IoT devices](https://www.cisco.com/c/en/us/solutions/enterprise-networks/edge-computing-architecture-5g.html)? Is it technology to enable [VR and self-driving cars](https://www.wired.com/story/its-time-to-think-beyond-cloud-computing/) or [smart homes](https://medium.com/velotio-perspectives/a-beginners-guide-to-edge-computing-6cfea853aa11)? The term seems so broad as to be almost meaningless.

More fundamentally, I am concerned that the "edge" buzzword is firmly in the control of big infrastructure providers ([cloud](https://azure.microsoft.com/en-us/solutions/low-latency-edge-computing/), [telcos](https://enterprise.verizon.com/business/learn/edge-computing/), [CDNs](https://www.akamai.com/uk/en/about/events/edgeworld.jsp), [enterprise vendors](https://www.ibm.com/cloud/what-is-edge-computing)), who are seeking to extend their power and control towards the edge. That seems incompatible with an ethos that is centered on giving control back to the end users, and reducing our dependence on infrastructure providers. Most of the arguments in favour of "edge" seem to be around lower latency and higher bandwidth compared to the cloud, whereas our motivation for preferring local over remote is an argument about greater resilience, autonomy, and control.

"local-first" is not "local-only", but rather "cloud-second": that is, there's nothing wrong with using cloud services as an optional enabling component, but we'd rather not have them on the critical path for the functioning of the system if we can avoid them. And I would say that the same goes for most of the "edge" services sold by the vendors linked above.

When we were trying to come up with the term that became "local-first", we also considered a bunch of alternatives, some of which are listed [in this thread](https://twitter.com/martinkl/status/1197477327686508546), and I think "local-first" was the best candidate. You're welcome to use that term if you like it.

**Comment by rkuhn** [comment]
Great input, thanks! Just a little clarification: in the second to last paragraph, have you forgotten a negation?

I agree that “local” better captures the essence than “edge” — unless we assume that we can redefine that term. It also has a more direct connection via the normal dictionary entry (“edge” can mean a bunch of things). I’m not yet sold on the “first” part, though, it postulates an absolute meaning that does not feel right to me: “X first” leaves no room for alternatives, regardless of the context (i.e. the cloud could reasonably be “first” for some things). I am not convinced that what we’re trying to promote is without alternatives — it is a very useful tool for a wide range of problems, but certainly not for everything.

This is why I chose “native” as the qualifier. This characterises the approach as fitting very well into a some environment. “Local native” does not really work, though, because it sounds like a duplication when read in a general English context.

Thanks for the link to the thread, very insightful! I agree with Peter that “offline” is also not the right word. I think I’ll have to do some cycling meditation to fully process the inputs and hopefully get more ideas.

**Comment by ept** [comment]
> in the second to last paragraph, have you forgotten a negation?

Not sure, which sentence?

> “X first” leaves no room for alternatives, regardless of the context (i.e. the cloud could reasonably be “first” for some things)

We chose the term by analogy to the established terms ["offline-first"](http://offlinefirst.org/) and ["mobile-first"](https://www.uxpin.com/studio/blog/a-hands-on-guide-to-mobile-first-design/). In those terms I don't think "first" is interpreted in an exclusive way (we still want apps to work while online, and we still want support for desktop computers), but rather as a reorientation of priorities, treating offline/mobile support as a first-class concern on par with online/desktop support.

I do like "native" too, but agree with your assessment that "local native" does not make much sense.

But of course it's your call, and by all means take time to think about it :)

**Comment by rkuhn** [comment]
> Not sure, which sentence?

I mean: “ … but we'd rather not have them on the critical path for the functioning of the system if we can avoid them. And I would say that the same goes for most of the "edge" services sold by the vendors linked above.” Perhaps I misunderstand “the same goes for” — do you say that those other vendors also avoid having the cloud on the critical path, or the opposite?

The reason why I find your objection to “edge” valid is that the issue is not only the involvement of the cloud, we’re aiming to remove _all_ unnecessary components from the critical path, including those that are called “edge services” but still are central (e.g. cell towers or nearby data centres). Getting cloud services closer to the edge devices (here “edge” seems to have a clearer meaning!) will be very beneficial, but in a complementary way and not for the critical path (in other words, it may be critical for some different non-local service, but that service is not delivered at real-time like the local service we talk about).

So, to propose an obvious dud that illustrates my desired semantics: “edge device native” seems to come close to what I want to say, since “edge device” seems to have a narrower connotation than “edge”. Not all edge devices are mobile, so what I’m looking for is a term that denotes these devices and their constraints (i.e. typically only limited storage and consumer-grade CPU — which is _a lot already_).

**Comment by ept** [comment]
Sorry, I meant that we don't want cloud services on the critical path for communication between physically co-located devices, and we don't really want "edge services" from infrastructure providers on that critical path either, if it can be avoided. So I think we're in agreement :)

"edge device" is a reasonable term; I've sometimes used "end-user device" (although this term would be less appropriate to a machine/PLC in a factory, which is not one person's device).

**Comment by rkuhn** [comment]
While cycling did not yet bring enlightenment, perhaps @benjchristensen or @jboner have ideas or remarks as well.

**Comment by benjchristensen** [comment]
> I personally am not a big fan of the term "edge", because it seems to mean very different things to different people

I agree strongly with this. I am consistently confused by what people are referring to when the word edge is used. 

In the space I work in, I would think edge is referring to the first layer between data center and the WAN. Or maybe the POP. So even there it’s confusing. 

Will think more about this.

**Comment by rkuhn** [comment]
Still no inspiration, but at least I mapped the terrain a bit: I find “local” to be too unspecific, I’d like to capture the collaboration between edge devices if possible. The following words go in the right direction:

> neighbour, neighbourhood, vicinity, adjacent, proximate, colony, collective

What I like about these is that each of them implies more than one thing, the last two imply a larger number of things even. And they imply these things to be somehow close to each other and related.

There is precedent with “neighbour discovery” in Internet standards. In all parts of the world (perhaps with the exception of Germany :trollface: ), neighbours also have a mostly positive connotation, unless I’m mistaken.

“Vicinity”, “adjacent”, and “proximate” are more sterile and technical and therefore carry less of the collaborative vibe.

“Colony” and “collective” have been used in different ways, not only for ants, which may or may not be problematic.

We could also call it the “Ant-Like Computation Principles” :-)

Does any of the above ring true with you? Or spark a better idea?

**Comment by rkuhn** [comment]
Today I had one more thought: collaboration between autonomous _agents_ requires some form of _diplomacy_ or _dialogue_.

**Comment by rkuhn** [comment]
After quite some pondering I come to the conclusion that at this point we should aim to be as precise as possible and avoid misunderstandings: promoting these ideas will hopefully attract like-minded people from contexts and backgrounds we didn’t foresee, and I want them to clearly make the connection to what we are doing.

As such, I don’t think we’ll find a single term that fits the bill right now (we’ll certainly be more successful later, with more diverse inputs). How about the following:

- we publish a website with a title like “mobile edge, collaborative apps, local-first” (open for improvements!) and write down the principles we believe in as well as the greater goal of making humankind’s general usage of computing more robust
- we share this website via social media and with people we think might be interested
- we refine the content as we get more contributors
- we then, eventually, may pick or define a single term to push this further

@ept @benjchristensen what do you think of this plan?

**Comment by ept** [comment]
I think it's fine to articulate a philosophy without necessarily coining a buzzword for it. The title could even be something descriptive such as "Better robustness for systems of nearby devices" or suchlike. In general, it might be a good idea to lead with the *why* (increasing robustness to failures of network connectivity and cloud services) rather than the *how* (using local resources and local communication).

**Comment by rkuhn** [comment]
To conclude this issue, and while I’m still working on refining the website in the linked PR, I renamed this github organisation to “local-first-cooperation” as a **working title** — we need something as short as possible for DNS and email group names. Thanks Martin and Ben!
